//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_D" +
    "eliveryRequestPort")]
public interface Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPort
{
    
    // CODEGEN: Generating message contract since the operation Submit is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="Submit", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    SubmitResponse Submit(SubmitRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Microsoft.Samples.BizTalk.WCFBasicHttpReceiveAdapter.BizTalkApp.DeliveryRe" +
    "quest")]
public partial class DeliveryItem
{
    
    private string productIDField;
    
    private string amountField;
    
    private string addressField;
    
    private string deliveryNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string ProductID
    {
        get
        {
            return this.productIDField;
        }
        set
        {
            this.productIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string Amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeliveryNumber
    {
        get
        {
            return this.deliveryNumberField;
        }
        set
        {
            this.deliveryNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Microsoft.Samples.BizTalk.WCFBasicHttpReceiveAdapter.BizTalkApp.DeliveryCo" +
    "nfirmation")]
public partial class DeliveryItem1
{
    
    private string confirmtionNumberField;
    
    private string deliveryNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string ConfirmtionNumber
    {
        get
        {
            return this.confirmtionNumberField;
        }
        set
        {
            this.confirmtionNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeliveryNumber
    {
        get
        {
            return this.deliveryNumberField;
        }
        set
        {
            this.deliveryNumberField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SubmitRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.Samples.BizTalk.WCFBasicHttpReceiveAdapter.BizTalkApp.DeliveryRe" +
        "quest", Order=0)]
    public DeliveryItem DeliveryItem;
    
    public SubmitRequest()
    {
    }
    
    public SubmitRequest(DeliveryItem DeliveryItem)
    {
        this.DeliveryItem = DeliveryItem;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SubmitResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.Samples.BizTalk.WCFBasicHttpReceiveAdapter.BizTalkApp.DeliveryCo" +
        "nfirmation", Order=0)]
    public DeliveryItem1 DeliveryItem;
    
    public SubmitResponse()
    {
    }
    
    public SubmitResponse(DeliveryItem1 DeliveryItem)
    {
        this.DeliveryItem = DeliveryItem;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPortChannel : Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPortClient : System.ServiceModel.ClientBase<Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPort>, Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPort
{
    
    public Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPortClient()
    {
    }
    
    public Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SubmitResponse Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPort.Submit(SubmitRequest request)
    {
        return base.Channel.Submit(request);
    }
    
    public DeliveryItem1 Submit(DeliveryItem DeliveryItem)
    {
        SubmitRequest inValue = new SubmitRequest();
        inValue.DeliveryItem = DeliveryItem;
        SubmitResponse retVal = ((Microsoft_Samples_BizTalk_WCFBasicHttpReceiveAdapter_BizTalkApp_DeliveryProcess_DeliveryRequestPort)(this)).Submit(inValue);
        return retVal.DeliveryItem;
    }
}
