//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.MoustafaRefaat.com/BTSPracCourse", ConfigurationName="BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultipl" +
    "yRequest")]
public interface BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequest
{
    
    // CODEGEN: Generating message contract since the operation Operation_1 is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="Operation_1", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    Operation_1Response Operation_1(Operation_1Request request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BTSPracCourse.Orchestrations.Processor.MultiplyRequestSchema")]
public partial class Root
{
    
    private RootMultiply multiplyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public RootMultiply Multiply
    {
        get
        {
            return this.multiplyField;
        }
        set
        {
            this.multiplyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BTSPracCourse.Orchestrations.Processor.MultiplyRequestSchema")]
public partial class RootMultiply
{
    
    private string aValField;
    
    private string bValField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string AVal
    {
        get
        {
            return this.aValField;
        }
        set
        {
            this.aValField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string BVal
    {
        get
        {
            return this.bValField;
        }
        set
        {
            this.bValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BTSPracCourse.Orchestrations.Processor.ResponseSchema")]
public partial class Root1
{
    
    private RootResult resultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public RootResult Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BTSPracCourse.Orchestrations.Processor.ResponseSchema")]
public partial class RootResult
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class Operation_1Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BTSPracCourse.Orchestrations.Processor.MultiplyRequestSchema", Order=0)]
    public Root Root;
    
    public Operation_1Request()
    {
    }
    
    public Operation_1Request(Root Root)
    {
        this.Root = Root;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class Operation_1Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BTSPracCourse.Orchestrations.Processor.ResponseSchema", Order=0)]
    public Root1 Root;
    
    public Operation_1Response()
    {
    }
    
    public Operation_1Response(Root1 Root)
    {
        this.Root = Root;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequestChannel : BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequest, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequestClient : System.ServiceModel.ClientBase<BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequest>, BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequest
{
    
    public BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequestClient()
    {
    }
    
    public BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequestClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequestClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Operation_1Response BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequest.Operation_1(Operation_1Request request)
    {
        return base.Channel.Operation_1(request);
    }
    
    public Root1 Operation_1(Root Root)
    {
        Operation_1Request inValue = new Operation_1Request();
        inValue.Root = Root;
        Operation_1Response retVal = ((BTSPracCourse_Orchestrations_Processor_WcfMultiplierServiceClient_Port_BTSMultiplyRequest)(this)).Operation_1(inValue);
        return retVal.Root;
    }
}
